[book]
authors = ["Huajing"]
language = "en"
multilingual = false
src = "src"
title = "Ethernue-book"
description = "A book that teaches how to build a security solidity smart contract."

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/yuhuajing/ethernaut-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/yuhuajing/ethernaut-book/tree/main/{path}"
cname = "ethernut-book.com"

[preprocessor.katex]
after = ["links"]
